-- -- Create the users table
-- CREATE TABLE users (
--     user_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--     user_email VARCHAR(255) NOT NULL,
--     user_password VARCHAR(255) NOT NULL
-- )
-- -- Create the profiles table
-- CREATE TABLE profiles (
--     user_id INT NOT NULL,
--     description VARCHAR(255),
--     FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
-- )